"""Cross-platform linguistic services for Python and PyQt6 applications."""

from pyqt6_linguistic_tools.backends import (
    PyThesBackend,
    SpellCheckerBackend,
    SpyllsBackend,
    ThesaurusBackend,
)
from pyqt6_linguistic_tools.cache import (
    BackendCache,
    CacheStats,
    LinguisticResultCacheStats,
    ResultCache,
)
from pyqt6_linguistic_tools.catalog import (
    DictionaryCatalog,
    DictionaryCatalogEntry,
    load_dictionary_catalog,
)
from pyqt6_linguistic_tools.errors import (
    BackendOperationError,
    BackendResolutionError,
    BackendUnavailableError,
    DictionaryDiscoveryError,
    DictionaryCatalogError,
    DictionaryImportError,
    DictionaryValidationError,
    DictionaryLoadError,
    DictionaryNotFoundError,
    LinguisticError,
    PersonalDictionaryBackupError,
    PersonalDictionaryError,
    UnsupportedOperationError,
)
from pyqt6_linguistic_tools.models import (
    BackendCapabilities,
    BackendMetadata,
    BackendResolution,
    BackendResolutionCode,
    BackendResolutionDiagnostic,
    DictionaryMetadata,
    DictionaryCandidate,
    DictionaryBundleValidation,
    DictionaryInfo,
    DictionaryImportResult,
    DictionarySourcePriority,
    DictionaryValidationReport,
    LinguisticCapabilities,
    LinguisticComponentFailure,
    LinguisticServiceDiagnostic,
    ThesaurusEntry,
    ThesaurusMeaning,
    ValidationCheck,
    ValidationStatus,
)
from pyqt6_linguistic_tools.locales import locale_display_name, normalize_locale
from pyqt6_linguistic_tools.ignored import IgnoredWords, IgnoredWordsStore
from pyqt6_linguistic_tools.providers import (
    DEFAULT_LINUX_DICTIONARY_PATHS,
    DictionaryProvider,
    DirectoryDictionaryProvider,
    LinuxSystemDictionaryProvider,
    ManagedDictionaryProvider,
    UserDictionaryProvider,
)
from pyqt6_linguistic_tools.personal import (
    PersonalDictionary,
    PersonalDictionaryStore,
    normalize_personal_locale,
    normalize_personal_word,
)
from pyqt6_linguistic_tools.personal_backup import (
    BACKUP_FORMAT,
    BACKUP_VERSION,
    PersonalDictionaryBackupEntry,
    PersonalDictionaryBackupManager,
    PersonalDictionaryBackupPreview,
    PersonalDictionaryRestoreEntry,
    PersonalDictionaryRestoreResult,
    RestoreMode,
)
from pyqt6_linguistic_tools.registry import DictionaryRegistry
from pyqt6_linguistic_tools.resolver import (
    BackendResolver,
    SpellBackendResolver,
    ThesaurusBackendResolver,
)
from pyqt6_linguistic_tools.service import (
    DiagnosticHandler,
    LinguisticService,
    logging_diagnostic_handler,
)
from pyqt6_linguistic_tools.storage import (
    DictionaryStoragePaths,
    application_data_directory,
    dictionary_storage_paths,
)
from pyqt6_linguistic_tools.tokenizer import (
    TokenFilter,
    TokenizerConfig,
    UnicodeTokenizer,
    WordToken,
    tokenize,
)
from pyqt6_linguistic_tools.validation import (
    DictionaryValidator,
    regenerate_thesaurus_index,
)

__version__ = "0.1.0.dev0"

__all__ = [
    "BackendCache",
    "BackendCapabilities",
    "BackendMetadata",
    "BackendOperationError",
    "BackendResolution",
    "BackendResolutionCode",
    "BackendResolutionDiagnostic",
    "BackendResolutionError",
    "BackendResolver",
    "BackendUnavailableError",
    "BACKUP_FORMAT",
    "BACKUP_VERSION",
    "CacheStats",
    "DEFAULT_LINUX_DICTIONARY_PATHS",
    "DictionaryLoadError",
    "DictionaryCandidate",
    "DictionaryBundleValidation",
    "DictionaryCatalog",
    "DictionaryCatalogEntry",
    "DictionaryCatalogError",
    "DictionaryDiscoveryError",
    "DictionaryInfo",
    "DictionaryImportError",
    "DictionaryImportResult",
    "DictionaryMetadata",
    "DictionaryNotFoundError",
    "DictionaryProvider",
    "DictionaryRegistry",
    "DictionarySourcePriority",
    "DictionaryStoragePaths",
    "DictionaryValidationReport",
    "DictionaryValidator",
    "DictionaryValidationError",
    "DiagnosticHandler",
    "DirectoryDictionaryProvider",
    "LinguisticError",
    "LinguisticCapabilities",
    "LinguisticComponentFailure",
    "LinguisticService",
    "LinguisticServiceDiagnostic",
    "LinuxSystemDictionaryProvider",
    "logging_diagnostic_handler",
    "LinguisticResultCacheStats",
    "IgnoredWords",
    "IgnoredWordsStore",
    "ManagedDictionaryProvider",
    "PersonalDictionary",
    "PersonalDictionaryBackupEntry",
    "PersonalDictionaryBackupError",
    "PersonalDictionaryBackupManager",
    "PersonalDictionaryBackupPreview",
    "PersonalDictionaryError",
    "PersonalDictionaryRestoreEntry",
    "PersonalDictionaryRestoreResult",
    "PersonalDictionaryStore",
    "PyThesBackend",
    "RestoreMode",
    "ResultCache",
    "SpellCheckerBackend",
    "SpellBackendResolver",
    "SpyllsBackend",
    "ThesaurusBackend",
    "ThesaurusBackendResolver",
    "ThesaurusEntry",
    "ThesaurusMeaning",
    "TokenFilter",
    "TokenizerConfig",
    "UnicodeTokenizer",
    "UnsupportedOperationError",
    "UserDictionaryProvider",
    "ValidationCheck",
    "ValidationStatus",
    "WordToken",
    "application_data_directory",
    "dictionary_storage_paths",
    "load_dictionary_catalog",
    "locale_display_name",
    "normalize_locale",
    "normalize_personal_locale",
    "normalize_personal_word",
    "regenerate_thesaurus_index",
    "tokenize",
    "__version__",
]
